package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.example.cayenne.persistent.Artist;
import org.example.cayenne.persistent.Gallery;

/**
 * Class _Painting was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Painting extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Artist>> ARTIST = Property.create("artist", List.class);
    public static final Property<List<Gallery>> GALLERYS = Property.create("gallerys", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToArtist(Artist obj) {
        addToManyTarget("artist", obj, true);
    }
    public void removeFromArtist(Artist obj) {
        removeToManyTarget("artist", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Artist> getArtist() {
        return (List<Artist>)readProperty("artist");
    }


    public void addToGallerys(Gallery obj) {
        addToManyTarget("gallerys", obj, true);
    }
    public void removeFromGallerys(Gallery obj) {
        removeToManyTarget("gallerys", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Gallery> getGallerys() {
        return (List<Gallery>)readProperty("gallerys");
    }


}
